import os

TELEGRAM_BOT_TOKEN = os.environ.get("ASSISTANT_FACTORY_BOT_TOKEN")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_DB = os.environ.get("POSTGRES_DB")
