version: '3.7'

services:
  bot:
    build:
      context: ./bot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"
  
  dozzle:
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_FILTER="status=running"
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres:16
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env