version: '3.7'

services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"