version: '3.7'

services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"
  
  dozzle:
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080
